name: swapi_repository
description: A dart package that implement a client of famous swapi RESTful
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
